### ISSUE TITLE
ErrorFetchingCatalog: 'AtlasBroker' object has no attribute 'catalog'

### ISSUE THREAD

**Issue by szwed** [mickybart/python-atlasbroker#1]
When trying to fetch atlas-broker Catalog I see this:
```
19:40 $ svcat get brokers
      NAME                                  URL                                     STATUS
+--------------+-----------------------------------------------------------+----------------------+
  atlas-broker   http://atlas-broker.atlas-broker.svc.cluster.local          ErrorFetchingCatalog
  ups-broker     http://ups-broker-ups-broker.ups-broker.svc.cluster.local   Ready
```

atlas-broker  logs:
```
12/03/2018 18:45:10 - INFO - werkzeug - 100.114.5.4 - - [12/Mar/2018 18:45:10] "GET /v2/catalog HTTP/1.1" 500 -
12/03/2018 18:46:32 - INFO - werkzeug - 100.114.5.4 - - [12/Mar/2018 18:46:32] "GET /v2/catalog HTTP/1.1" 500 -
12/03/2018 18:46:32 - ERROR - root - 'AtlasBroker' object has no attribute 'catalog'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/openbrokerapi/api.py", line 87, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/openbrokerapi/api.py", line 148, in catalog
    return to_json_response(CatalogResponse(list(s.catalog() for s in service_brokers)))
  File "/usr/local/lib/python3.6/site-packages/openbrokerapi/api.py", line 148, in <genexpr>
    return to_json_response(CatalogResponse(list(s.catalog() for s in service_brokers)))
AttributeError: 'AtlasBroker' object has no attribute 'catalog'
✔ ~/python-atlasbroker/k8s [master|✚ 3]
```

It seems like it is supported by openbrokerapi:
https://github.com/eruvanos/openbrokerapi/blob/master/openbrokerapi/api.py#L142

But there must be some problem there:
https://github.com/eruvanos/openbrokerapi/blob/master/openbrokerapi/api.py#L148

**Comment by mickybart** [comment]
Thanks for the report, openbrokerapi bumped from 1.0 to 2.0.
https://pypi.python.org/pypi/openbrokerapi/2.0.0

The current code is tested with openbrokerapi 1.0 and they changed the way to deliver the /v2/catalog.

For now  you can force to install openbrokerapi 1.0.0 instead of the last one to fix the issue.

I will update the atlasbroker to fit openbrokerapi 2.0.0. They created a "def catalog(self)" function so it seems that I just need to move super().__init__(....) to a catalog function in service.py.

**Comment by szwed** [comment]
@mickybart I was trying to do that but there is only 2.0.0 available in the pypi repo:
https://pypi.python.org/pypi/openbrokerapi

Current requirements.txt will be always pulling 2.0.0, even <=2.0.0 switch fails as it can't find any older packages.

now giving a try to direct pull from github and 1.0.0 release...

**Comment by mickybart** [comment]
@szwed I tested it and I can pull the 1.0.0 version.
Here: https://pypi.python.org/pypi/openbrokerapi/1.0.0

In the requirements.txt, force openbrokerapi==1.0.0

cat requirements.txt
openbrokerapi==1.0.0
atlasbroker

It will work. (I'm doing the patch to use the 1.0.0 for now and I will check a little bit later to move to 2.0.0)

**Comment by mickybart** [comment]
@szwed , I pushed an new package atlasborker 1.1.3.
This version request openbrokerapi 1.0.0

see trace of pip:
Collecting openbrokerapi==1.0.0 (from atlasbroker==1.1.3->-r requirements.txt (line 1))
  Downloading openbrokerapi-1.0.0-py3-none-any.whl

1.1.2 will be replaced soon with 1.1.3 on pypi but if you need you can force it for now :
pip install atlasbroker>=1.1.3

**Comment by szwed** [comment]
Thanks, also works for me:

```
14:54 $ kubectl logs atlas-broker-867f5d85b4-gvx2w -n medialon-ovt
connection to mongo...
mongo: connected
13/03/2018 13:52:00 - INFO - werkzeug -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
13/03/2018 13:54:05 - INFO - werkzeug - 100.104.48.1 - - [13/Mar/2018 13:54:05] "GET /v2/catalog HTTP/1.1" 200 -
```

now testing the provisioning part...
