### ISSUE TITLE
Secret object is empty

### ISSUE THREAD

**Issue by szwed** [mickybart/python-atlasbroker#2]
I deployed atlas-broker in the same way as like it is described in the documentation and it seems to be working correctly:
```
14/03/2018 11:53:10 - INFO - werkzeug - 100.117.53.179 - - [14/Mar/2018 11:53:10] "GET /v2/catalog HTTP/1.1" 200 -
14/03/2018 13:39:49 - INFO - werkzeug - 100.117.53.179 - - [14/Mar/2018 13:39:49] "DELETE /v2/service_instances/1c0d5f68-c1c5-4fff-b9e7-829e6c0370e5/service_bindings/1d98ceeb-238a-4d40-a902-096caebf9068?plan_id=8db474d1-3cc0-4f4d-b864-24e3bd49b874&service_id=2a04f349-4aab-4fcb-af6d-8e1749a77c13 HTTP/1.1" 410 -
14/03/2018 13:41:02 - INFO - werkzeug - 100.117.53.179 - - [14/Mar/2018 13:41:02] "PUT /v2/service_instances/1c0d5f68-c1c5-4fff-b9e7-829e6c0370e5/service_bindings/ad363607-4d4f-4d51-857e-272be40ad2ee HTTP/1.1" 201 -
14/03/2018 13:41:02 - INFO - werkzeug - 100.117.53.179 - - [14/Mar/2018 13:41:02] "PUT /v2/service_instances/1c0d5f68-c1c5-4fff-b9e7-829e6c0370e5/service_bindings/ad363607-4d4f-4d51-857e-272be40ad2ee HTTP/1.1" 200 -
```

It created MongoDB user:
`ad363607-4d5f-4d51-857e-272ba40ad2ee@admin`

Only problem I still see are Secrets. Secret object is completely empty, here is the output:
```
14:38 $ kubectl describe secrets -n test-atlas-broker
Name:         atlas-broker-binding
Namespace:    test-atlas-broker
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
```
@mickybart could you help me with troubleshooting the problem? Where to start looking for? I do not see anything suspicious in atlas-broker logs.

**Comment by szwed** [comment]
Similar test done for atlas-broker and the official UPS example :

```
14:56 $ kubectl get secrets -n test-atlas-broker
NAME                   TYPE                                  DATA      AGE
atlas-broker-binding   Opaque                                0         15m
```
```
14:51 $ kubectl get secrets -n test-ns
NAME                  TYPE                                   DATA      AGE
ups-binding           Opaque                                 2         2h
```

DATA=0 for atlas-broker :(
DATA=2 for UPC

Any ideas what may be wrong?

**Comment by mickybart** [comment]
Hi @szwed ,

You have few things to check:
1/ output of the Atlas broker itself (mainly if there is no exception). In your case it seems to be fine.

2/ check status of the service instance and service binding
```
kubectl -n test-atlas-broker get serviceinstance atlas-broker-instance -o yaml
kubectl -n test-atlas-broker get servicebinding atlas-broker-binding -o yaml
```

You should see the status and message error of the binding and/or instance.

If the binding success, you should see:

```
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: 2018-03-14T15:17:14Z
    message: Injected bind result
    reason: InjectedBindResult
    status: "True"
    type: Ready
```

3/ You override the Config.generate_binding_credentials and this function do not return a dict or an empty one.

On my side, the prod is running kubernetes v1.8.6, and service catalog is from https://github.com/kubernetes-incubator/service-catalog/

I just create test-atlas-broker and it is working fine in this setup.
```
$ kubectl -n test-atlas-broker get secret
NAME                   TYPE                                  DATA      AGE
atlas-broker-binding   Opaque                                4         3m
...
```

I'm using a the class CustomConfig from the docker/run.py but there is nothing changed to generate credentials.

Let me know the result of your tests.

**Comment by szwed** [comment]
@mickybart Thanks for the answer, last question.. do you have RBAC enabled in your test cluster?

**Comment by mickybart** [comment]
@szwed , Yes RBAC is enabled. In fact we are not in test anymore. The service is now in real production.

**Comment by mickybart** [comment]
FYI I just faced the same issue after an upgrade of the service catalog.
I just checked that credentials are sent and this is the cas. So the catalog is able to create the secret but not to inject the data on it ! And it is reporting a bind success.
I will dig on it... 

Do you know on which service catalog version you are running ?

You can see it with :
kubectl -n service-catalog get deploy apiserver -o yaml | grep image

Thanks

PS: the version with openbrokerapi2 is near to be ready. Everything is working so I will probably release it sooner

**Comment by mickybart** [comment]
I tested with ups-broker in the same environment and I'm able to inject a secret.
The output of the atlas-broker binding seems correct:

```
< HTTP/1.0 201 CREATED
< Content-Type: application/json
< Content-Length: 531
< Server: Werkzeug/0.14.1 Python/3.6.5
< Date: Thu, 19 Apr 2018 19:02:43 GMT
< 
{
  "credentials": {
    "database": "...", 
    "password": "...", 
    "uri": "...", 
    "username": "..."
  }
}
```

EDIT:

The ouput of the ups-broker:
```
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 19 Apr 2018 19:34:26 GMT
< Content-Length: 85
< 
* Connection #0 to host localhost left intact
{"credentials":{"special-key-1":"special-value-1","special-key-2":"special-value-2"}}
```

There is no 201 used despite the norm should be to answer the first time with a 201.
I noticed that all other call on ups-broker return the same 200 OK with credentials. This is not the case with atlas-broker.

After reading the norm again maybe this is wrong and the source of the issue. I will continue to answer 201 as expected but I will check to include credentials on all other 200 Already Exist case (or an error if possible to avoid password changes).

Calls to atlas broker from service catalog:

```
19/04/2018 19:25:05 - INFO - werkzeug - 10.18.46.69 - - [19/Apr/2018 19:25:05] "PUT /v2/service_instances/e48ddd1f-a992-4721-9678-b0e78926fe96/service_bindings/17527817-00f2-4f70-96e9-6c060ff8e579 HTTP/1.1" 201 -
19/04/2018 19:25:05 - INFO - werkzeug - 10.18.46.69 - - [19/Apr/2018 19:25:05] "PUT /v2/service_instances/e48ddd1f-a992-4721-9678-b0e78926fe96/service_bindings/17527817-00f2-4f70-96e9-6c060ff8e579 HTTP/1.1" 200 -
19/04/2018 19:25:05 - INFO - werkzeug - 10.18.46.69 - - [19/Apr/2018 19:25:05] "PUT /v2/service_instances/e48ddd1f-a992-4721-9678-b0e78926fe96/service_bindings/17527817-00f2-4f70-96e9-6c060ff8e579 HTTP/1.1" 200 -
19/04/2018 19:25:06 - INFO - werkzeug - 10.18.46.69 - - [19/Apr/2018 19:25:06] "PUT /v2/service_instances/e48ddd1f-a992-4721-9678-b0e78926fe96/service_bindings/17527817-00f2-4f70-96e9-6c060ff8e579 HTTP/1.1" 200 -
```

The first one (201) create the secrets and I suspect all other 200 to clear those secrets. I still don't know what change is responsible of this but I will first check to validate this theory and see the best way to fix it as the generated password is not stored anywhere.

**Comment by mickybart** [comment]
@szwed , the branch fixsecrets permit to fix this issue and rely on openbrokerapi 2 too. Can you give it a try if possible ?

I will rework the patch to have something configurable from the config.py in the master branch.

**Comment by mickybart** [comment]
Just pushed the fix and openbrokerapi 2.0 compatibility with atlasbroker-2.0.0-py3-none-any.whl
Tested with success on my side.
I added an extra function in the config.py to handle this case depending on which way  generate_binding_credentials function is working.

**Comment by szwed** [comment]
@mickybart - big thanks for the updates, I have asked my colleague who took over responsibility for atlas-broker integration to give you an update today. As far as I know it works pretty well right now. We are also going to try the latest version with openbrokerapi 2.0 support, we will let you know how it works for us.

**Comment by thereallukl** [comment]
I took over from @szwed deploying it on our cluster. I rebased code to version from this commit https://github.com/mickybart/python-atlasbroker/commit/6c9180fdb60e1d14bbd0aea76c848afad395e361 and it works like a charm :)

**Comment by mickybart** [comment]
Thanks a lot for your feedback.
